labels:
  env: dev
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/satveerkhurpa/eks-blueprints-workloads
    targetRevision: main

  # Thoses default values can be surcharged by Infrastructure as Code
  env: dev
  clusterName: external-dns # the name of EKS cluster
  blueprint: 'terraform' # cdk | terraform
  karpenterInstanceProfile:
  ingress:
    type: 'nginx' # nginx | alb
    host: # empty or your domain like dev.example.com
